# Generated by Django 4.1.1 on 2022-09-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
